FROM golang:1.22.7-alpine AS base

FROM base AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o hello-server .

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/hello-server .
EXPOSE 8080
CMD ["./hello-server"]
